AWSTemplateFormatVersion: '2010-09-09'
Description: 'chaos-lambda

  Sample SAM Template for chaos-lambda

  '
Globals:
  Function:
    Timeout: 300
Resources:
  LambdaFunction:
    Properties:
      CodeUri: s3://sam-template-packaged/80e98a7d830534af78e49f4b9b826c50
      Environment:
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Properties:
            Method: get
            Path: /chaos-lambda/delete
          Type: Api
      Handler: app.lambdaHandler
      Role:
        Fn::GetAtt:
        - LambdaRole
        - Arn
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
  LambdaRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: '2012-10-17'
      Path: /
      Policies:
      - PolicyDocument:
          Statement:
          - Action: ec2:*
            Effect: Allow
            Resource: '*'
          Version: '2012-10-17'
        PolicyName: chaos-lambda-delete-ec2-lambda-policy
      RoleName: chaos-lambda-delete-ec2-lambda-role
    Type: AWS::IAM::Role
Transform: AWS::Serverless-2016-10-31
